# CloudMan settings
cm_cluster_type: "{{ lookup('env', 'CM_CLUSTER_TYPE')|default('KUBE_RANCHER', true) }}"
cm_initial_cluster_data: "{{ lookup('env', 'CM_INITIAL_CLUSTER_DATA') }}"
cm_initial_storage_size: "{{ lookup('env', 'CM_INITIAL_STORAGE_SIZE')|default('100Gi', true) }}"
cm_helm_values: "{{ lookup('env', 'CM_HELM_VALUES') }}"
cvmfs_helm_values: "{{ lookup('env', 'CVMFS_HELM_VALUES') }}"
cm_skip_cloudman: "{{ lookup('env', 'CM_SKIP_CLOUDMAN')|default('false', true) }}"
cm_cluster_name: cloudman-cluster
cm_namespace_name: cloudman
cm_chart_version: 0.3.1
cm_deployment_name: "{{ lookup('env', 'CM_DEPLOYMENT_NAME') }}"

# cloud provider for this cluster:
# ref: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/
# ref: https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/
kube_cloud_provider: "{{ lookup('env', 'KUBE_CLOUD_PROVIDER') }}"
kube_cloud_conf: "{{ lookup('env', 'KUBE_CLOUD_CONF') }}"

# Rancher settings
rancher_name: rancher_server
rancher_server: "{{ lookup('env', 'RANCHER_SERVER')|default(hostvars['localhost']['ansible_facts']['default_ipv4']['address'], true) }}"
rancher_version: v2.2.9
rancher_port: 4430
rancher_port_http: 8080
rancher_admin: admin
rancher_password: "{{ lookup('env', 'RANCHER_PWD') }}"
# The following variables define roles the master node will take. Values must
# be either `--etcd`, `--controlplane`, and `--worker` for respective variable
# or set to a blank value (i.e., ``)
rancher_master_etcd: "{{ lookup('env', 'RANCHER_MASTER_ETCD')|default('--etcd', true) }}"
rancher_master_controlplane: "{{ lookup('env', 'RANCHER_MASTER_CONTROLPLANE')|default('--controlplane', true) }}"
rancher_master_as_worker: "{{ lookup('env', 'RANCHER_MASTER_WORKER')|default('--worker', true) }}"

# Used when no rancher password is specified
random_pwd: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
# Used for generating oidc client secret
random_client_secret: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') | lower }}-{{ lookup('password', '/dev/null length=4 chars=ascii_letters,digits') | lower }}-{{ lookup('password', '/dev/null length=4 chars=ascii_letters,digits') | lower }}-{{ lookup('password', '/dev/null length=4 chars=ascii_letters,digits') | lower }}-{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') | lower }}"
