- name: Create CloudMan chart template file
  template:
    src: cm_chart_values.yml.j2
    dest: /tmp/template_cm_chart_values.j2

- name: Render CloudMan chart custom values file
  template:
    src: /tmp/template_cm_chart_values.j2
    dest: /tmp/cm_chart_values.yml

- name: Delete existing CRDs
  command: "kubectl delete crd {{ item }}"
  with_items:
  - prometheusrules.monitoring.coreos.com
  - servicemonitors.monitoring.coreos.com
  - alertmanagers.monitoring.coreos.com
  - prometheuses.monitoring.coreos.com
  - podmonitors.monitoring.coreos.com
  ignore_errors: true

- name: Helm install CloudMan
  command: >
    /usr/local/bin/helm install cloudman galaxyproject/cloudman
    --namespace "{{ cm_namespace_name }}"
    --version "{{ cm_chart_version }}"
    -f /tmp/cm_chart_values.yml
  ignore_errors: true
